#!/bin/bash
g++ -O3 pair.cpp randomizer.c init.cpp -o pair
echo "--- pair ---"
./pair osman hasan ali
./pair < names.txt

g++ -O3 grouper.cpp randomizer.c init.cpp set.c -o grouper
echo "--- grouper ---"
./grouper 2 osman hasan ali        # group by 2
./grouper 3 names.txt              # group file by 3
cat names2.txt | ./grouper 5       # pipe group by 5
